cors: 
  - *
host: 127.0.0.1
port: 8080
authKey: KeyofMiraiHttpApi
cacheSize: 8192
enableWebsocket: true
report: 
  enable: true
  groupMessage: 
    report: true
  friendMessage: 
    report: true
  tempMessage: 
    report: true
  eventMessage: 
    report: true
  destinations: []
  extraHeaders: 
{}

heartbeat: 
  enable: true
  delay: 1000
  period: 15000
  destinations: []
  extraBody: 
{}

  extraHeaders: 
{}
